<?php

/**
 * Abstract theme class.
 *
 * @package EightshiftForms
 */

declare(strict_types=1);

namespace EightshiftForms\Theme;

/**
 * Abstract theme class.
 */
abstract class AbstractTheme
{
	/**
	 * Admin selectors.
	 *
	 * @var array<mixed>
	 */
	public const THEME_SELECTORS = [
		'input' => [
			'esf:w-full',
			'esf:border',
			'esf:border-gray-300',
			'esf:bg-white',
			'esf:p-8',
			'esf:rounded-lg',
			'esf:text-xs',
			'esf:text-black',
			'esf:h-40',
			'esf:shadow-none',
			'esf:placeholder:text-gray-400',
			'esf:field-disabled:bg-gray-50',
			'esf:field-disabled:text-gray-500',
			'esf:field-disabled:cursor-not-allowed',
			'esf:field-disabled:border-gray-300',
			'esf:focus-ring',
			'esf:field-error:border-red-500',
		],
		'help' => [
			'esf:text-gray-400',
			'esf:text-xs',
			'esf:[&_a]:text-mauve-600',
			'esf:[&_a]:underline',
			'esf:[&_a]:hover:text-mauve-700',
			'esf:focus-ring'
		],
		'help-extended' => [
			'esf:[&_ul]:list-disc',
			'esf:[&_ul]:list-inside',
			'esf:[&_ul]:m-0',
			'esf:[&_ul]:p-0',
			'esf:[&_ul]:gap-5',
			'esf:[&_ul]:flex',
			'esf:[&_ul]:flex-col',
			'esf:[&_li]:m-0',
			'esf:[&_code]:text-gray-400',
			'esf:[&_code]:text-xs!',
			'esf:[&_code]:font-mono!',
			'esf:[&_code]:m-0',
			'esf:[&_code]:px-3',
			'esf:[&_code]:py-1',
			'esf:[&_code]:bg-gray-100',
			'esf:focus-ring',
		],
		'after-content' => [
			'esf:text-gray-600',
			'esf:text-xs',
		],
		'label' => [
			'esf:text-base',
			'esf:block',
			'esf:p-0',
		],
		'select' => [
			'base' => [
				'esf:group/select',
				'esf:relative',
				'esf:text-xs',
				'esf:text-black',
				'esf:focus-ring-clear',

				'esf:choices-one-inner:h-40',
				'esf:choices-one-inner:flex',
				'esf:choices-one-inner:items-center',
				'esf:choices-one-inner:p-10',
				'esf:choices-one-inner:pr-55',
				'esf:choices-one-inner:[&_.choices\_\_placeholder]:text-gray-400',
				'esf:choices-one-inner:[&_.choices\_\_placeholder]:[&_.choices\_\_button]:hidden',
				'esf:choices-one-inner:[&_.choices\_\_list]:w-full',
				'esf:choices-one-inner:[&_.choices\_\_item]:truncate',

				'esf:choices-multi-inner:w-full',
				'esf:choices-multi-inner:min-h-40',
				'esf:choices-multi-inner:inline-block',
				'esf:choices-multi-inner:pt-6',
				'esf:choices-multi-inner:pl-10',
				'esf:choices-multi-inner:pr-5',
				'esf:choices-multi-inner:align-bottom',
				'esf:choices-multi-inner:[&_.choices\_\_list]:inline',
				'esf:choices-multi-inner:[&_.choices\_\_list]:align-top',
				'esf:choices-multi-item:inline-block',
				'esf:choices-multi-item:align-middle',
				'esf:choices-multi-item:rounded-full',
				'esf:choices-multi-item:py-4',
				'esf:choices-multi-item:pl-10',
				'esf:choices-multi-item:pr-35',
				'esf:choices-multi-item:bg-mauve-600',
				'esf:choices-multi-item:text-white',
				'esf:choices-multi-item:relative',
				'esf:choices-multi-item:mr-7',
				'esf:choices-multi-item:mb-6',
				'esf:choices-multi-button:top-0',
				'esf:choices-multi-button:right-0',
				'esf:choices-multi-button:h-full',
				'esf:choices-multi-button:w-30',
				'esf:choices-multi-button:text-white',
				'esf:choices-multi-button:hover:text-mauve-700',
				'esf:choices-multi-button:focus:rounded-full',
				'esf:choices-multi-cloned:border-0',
				'esf:choices-multi-cloned:min-h-30',
				'esf:choices-multi-cloned:h-30',
				'esf:choices-multi-cloned:p-0',
				'esf:choices-multi-cloned:m-0',
				'esf:choices-multi-cloned:focus-ring-clear',
				'esf:choices-multi-cloned:placeholder:text-gray-400',
				'esf:choices-multi-cloned:text-base',
			],
			'parts' => [
				'select-choices-inner' => [
					'esf:group/select-inner',
					'esf:relative',
					'esf:text-base',
					'esf:text-black',
					'esf:bg-white',
					'esf:border',
					'esf:border-gray-300',
					'esf:rounded-lg',
					'esf:overflow-hidden',
					'esf:cursor-pointer',

					'esf:[&_select]:hidden-fully',

					'esf:group-[&.is-focused]/select:focus-ring-direct',

					"esf:after:content-['']",
					"esf:after:h-0",
					"esf:after:w-0",
					"esf:after:border-solid",
					"esf:after:border-transparent",
					"esf:after:border-t-mauve-200",
					"esf:after:border-7",
					"esf:after:absolute",
					"esf:after:right-10",
					"esf:after:top-19",
					"esf:after:pointer-events-none",

					'esf:field-error:border-red-500',

					'esf:field-disabled:text-gray-400',
					'esf:field-disabled:bg-gray-100',
					'esf:field-disabled:cursor-not-allowed',
				],
				'select-list' => [
					'esf:m-0',
					'esf:pl-0',
					'esf:list-none',
				],
				'select-list-dropdown' => [
					'esf:hidden',
					'esf:z-100',
					'esf:absolute',
					'esf:w-full',
					'esf:bg-white',
					'esf:border',
					'esf:border-mauve-200',
					'esf:top-full',
					'esf:inset-x-0',
					'esf:mt-2',
					'esf:rounded-lg',
					'esf:overflow-hidden',
					'esf:break-all',

					'esf:group-[&.is-open]/select:block',
					'esf:field-disabled:hidden!',

					'esf:[&_.choices\_\_list]:relative',
					'esf:[&_.choices\_\_list]:max-h-300',
					'esf:[&_.choices\_\_list]:overflow-auto',
					'esf:[&_.choices\_\_list]:will-change-scroll',

					'esf:[&_.choices\_\_item]:relative',
					'esf:[&_.choices\_\_item]:p-10',

					'esf:[&_.choices\_\_placeholder]:hidden-fully',

					'esf:[&_.choices\_\_input]:w-full!',
					'esf:[&_.choices\_\_input]:min-w-full!',
					'esf:[&_.choices\_\_input]:p-10',
					'esf:[&_.choices\_\_input]:border-0',
					'esf:[&_.choices\_\_input]:border-b',
					'esf:[&_.choices\_\_input]:border-mauve-200',
					'esf:[&_.choices\_\_input]:rounded-none',
					'esf:[&_.choices\_\_input]:bg-transparent',
					'esf:[&_.choices\_\_input]:focus-ring-clear',

					'esf:[&_.choices\_\_item--selectable]:cursor-pointer',
					'esf:[&_.choices\_\_item--selectable]:hover:bg-mauve-600/30',
					'esf:[&_.choices\_\_item--selectable]:[&.is-highlighted]:bg-mauve-600/30',
					'esf:[&_.choices\_\_item--selectable]:[&.is-selected]:bg-mauve-600',
					'esf:[&_.choices\_\_item--selectable]:[&.is-selected]:text-white',

					"esf:[&_.choices\_\_item[data-option-is-hidden='1']]:hidden-fully",
				],
				'select-item-disabled' => [
					'esf:opacity-50',
					'esf:cursor-not-allowed',
				],
				'select-button' => [
					'esf:appearance-none',
					'esf:border-0',
					'esf:bg-transparent',
					'esf:bg-no-repeat',
					'esf:bg-center',
					'esf:cursor-pointer',
					'esf:p-0',
					'esf:absolute',
					'esf:top-8',
					'esf:right-30',
					'esf:text-lg',
					'esf:w-29',
					'esf:h-29',
					'esf:flex',
					'esf:items-center',
					'esf:justify-center',
					'esf:text-mauve-600',
					'esf:hover:text-mauve-700',
					'esf:focus-ring',
				]
			],
		],
		'checkbox' => [
			'parts' => [
				'input' => [
					'esf:relative',
					'esf:appearance-none',
					'esf:bg-white',
					'esf:border',
					'esf:items-center',
					'esf:mx-0!',
					'esf:my-auto!',
					'esf:shadow-none',
					'esf:transition',
					'esf:cursor-pointer',
					'esf:border-gray-300',
					'esf:focus-ring',

					'esf:after:flex',
					'esf:after:items-center',
					'esf:after:justify-center',
					'esf:after:text-base',
					'esf:after:transition',
					'esf:after:absolute',

					'esf:checked:bg-mauve-500',
					'esf:checked:border-mauve-500',

					'esf:is-check:size-24',
					'esf:is-check:after:left-2',
					'esf:is-check:after:top-2',
					'esf:is-check:not-checked:after:opacity-0',
					'esf:is-check:after:text-white',
				],
				'content' => [
					'esf:flex',
					'esf:items-center',
					'esf:gap-10',
				],
			],
		],
	];

	/**
	 * Get the theme selectors for admin and frontend.
	 *
	 * @return array<string, mixed>
	 */
	public function getTheme(): array
	{
		return [
			'forms' => [
				'base' => [
					'esf:relative',
					'esf:box-mauve-200',
					'esf:[&_*]:box-mauve-200',
					'esf:[&_:after]:box-mauve-200',
					'esf:[&_:before]:box-mauve-200',
				],
			],
			'form' => [
				'base' => [
					'esf:group/form',
					'esf:flex',
					'esf:flex-col',
					'esf:gap-10',
					'esf:text-base',
					'esf:[&_*]:transition-colors',
					'esf:[&_*]:duration-300',
				],
				'parts' => [
					'fields' => [
						'esf:grid',
						'esf:gap-20',
						'esf:grid-cols-12',
					],
				],
			],
			'field' => [
				'base' => [
					'esf:group/field',
					'esf:relative',
					'esf:flex',
					'esf:flex-col',
					'esf:gap-10',
					'esf:border-none',
					'esf:min-w-0',
					'esf:col-end-span-[var(--es-field-width-tw,12)]',
				],
				'parts' => [
					'inner' => [
						'esf:flex',
						'esf:flex-col',
						'esf:gap-5',
					],
					'content' => [
						'esf:flex',
						'esf:flex-col',
						'esf:gap-5',
					],
					'content-wrap' => [
						'esf:flex',
						'esf:flex-col',
						'esf:gap-10',
					],
					'label' => [
						...self::THEME_SELECTORS['label'],
						'esf:group/label',
					],
					'label-inner' => [
						"esf:label-required:after:content-['*']",
						'esf:label-required:after:text-red-500',
						'esf:label-required:after:text-base',
						'esf:label-required:after:font-semibold',
						"esf:group-[&.es-field\_\_label--is-visually-hidden]/label:sr-only",
					],
					'help' => self::THEME_SELECTORS['help'],
					'suffix-content' => self::THEME_SELECTORS['after-content'],
					'before-content' => self::THEME_SELECTORS['after-content'],
					'after-content' => self::THEME_SELECTORS['after-content'],
					'debug' => [
						'esf:opacity-0',
						'esf:text-xs',
						'esf:text-gray-500',
						'esf:p-5',
						'esf:border',
						'esf:border-mauve-200',
						'esf:rounded-lg',
						'esf:pointer-events-none',
						'esf:absolute',
						'esf:right-0',
						'esf:top-0',
						'esf:z-10',
						'esf:bg-white',
						'esf:transition-opacity',
						'esf:duration-300',
						'esf:group-hover/field:opacity-100',
					],
					'error' => [
						'esf:text-red-500',
						'esf:text-sm',
						'esf:hidden',
						'esf:field-error:block',
					],
				],
			],
			'input' => [
				'base' => self::THEME_SELECTORS['input'],
			],
			'date' => [
				'base' => self::THEME_SELECTORS['input'],
				'parts' => [
					'picker' => [
						// Picker is not part of the form.
						'esf:[&_*]:transition-colors',
						'esf:[&_*]:duration-300',
						'esf:text-black',
						'esf:shadow-none',
						'esf:rounded-lg',
						'esf:border',
						'esf:border-mauve-200',
						'esf:text-base',
						'esf:[&_.flatpickr-day]:hover:text-white',
						'esf:[&_.flatpickr-day]:hover:bg-mauve-600',
						'esf:[&_.flatpickr-day]:hover:border-mauve-600',
						'esf:[&_.flatpickr-day]:focus-ring!',

						'esf:[&_.selected]:text-white!',
						'esf:[&_.selected]:bg-mauve-600!',
						'esf:[&_.selected]:border-mauve-600!',
						'esf:[&_.selected]:hover:bg-mauve-600!',
						'esf:[&_.selected]:focus:bg-mauve-600!',
						'esf:[&_.selected]:focus:border-mauve-600!',
						'esf:[&_.today]:bg-white',
						'esf:[&_.today]:border-mauve-400',
						'esf:[&_.flatpickr-next-month:hover>svg]:fill-mauve-600',
						'esf:[&_.flatpickr-prev-month:hover>svg]:fill-mauve-600',
					]
				]
			],
			'textarea' => [
				'base' => [
					...self::THEME_SELECTORS['input'],
					'esf:min-h-200',
					'esf:h-auto',
				],
			],
			'checkbox' => [
				'parts' => [
					'input' => [
						...self::THEME_SELECTORS['checkbox']['parts']['input'],
						'esf:is-check:rounded-lg',
						'esf:is-check:before:hidden!',
						'esf:is-check:after:content-["✓"]',
						'esf:is-check:after:size-18',
					],
					'content' => self::THEME_SELECTORS['checkbox']['parts']['content'],
					'label' => self::THEME_SELECTORS['label'],
					'help' => self::THEME_SELECTORS['help'],
				],
			],
			'radio' => [
				'parts' => [
					'input' => [
						...self::THEME_SELECTORS['checkbox']['parts']['input'],
						'esf:is-check:rounded-full',
						'esf:is-check:after:content-["•"]',
						'esf:is-check:after:w-18',
						'esf:is-check:after:h-13',
						'esf:is-check:after:text-5xl',
					],
					'content' => self::THEME_SELECTORS['checkbox']['parts']['content'],
					'label' => self::THEME_SELECTORS['label'],
					'help' => self::THEME_SELECTORS['help'],
				],
			],
			'range' => [
				'base' => [
					'esf:appearance-none',
					'esf:p-0',
					'esf:m-0',
					'esf:block-size-10',
					'esf:w-full',
					'esf:bg-none',
					'esf:focus-ring-clear',
					'esf:field-disabled:cursor-not-allowed',

					'esf:slider-track:appearance-none',
					'esf:slider-track:bg-white',
					'esf:slider-track:border',
					'esf:slider-track:border-mauve-200',
					'esf:slider-track:rounded-full',
					'esf:slider-track:h-10',
					'esf:slider-track:w-full',
					'esf:field-disabled:slider-track:border-gray-100',

					'esf:slider-thumb:appearance-none',
					'esf:slider-thumb:bg-mauve-600',
					'esf:slider-thumb:border-mauve-600',
					'esf:slider-thumb:rounded-full',
					'esf:slider-thumb:h-20',
					'esf:slider-thumb:w-20',
					'esf:slider-thumb:-mt-5',
					'esf:slider-thumb:cursor-pointer',
					'esf:slider-thumb:transition-colors',
					'esf:slider-thumb:duration-300',
					'esf:focus:slider-thumb:focus-ring-direct',
					'esf:focus:slider-thumb:rounded-full',

					'esf:[&::-moz-range-progress]:bg-mauve-600',
					'esf:[&::-moz-range-progress]:appearance-none',
					'esf:[&::-moz-range-progress]:rounded-full',
					'esf:[&::-moz-range-progress]:h-10',
					'esf:[&::-moz-range-progress]:w-full',
					'esf:disabled:[&::-moz-range-progress]:bg-gray-100',
				],
				'parts' => [
					'min' => '',
					'max' => '',
					'current' => '',
					'output' => [
						'esf:flex',
						'esf:flex-row',
						'esf:items-center',
						'esf:justify-between',
						'esf:gap-5',
						'esf:text-sm',
					],
					'custom' => self::THEME_SELECTORS['input'],
					'field-content-wrap' => [
						"esf:group-[[data-has-custom-range-input='1']]/field:grid",
						"esf:group-[[data-has-custom-range-input='1']]/field:gap-10",
						"esf:group-[[data-has-custom-range-input='1']]/field:grid-cols-[1fr_min(140px)]",
					],
				],
			],
			'select' => [
				'base' => self::THEME_SELECTORS['select']['base'],
				'parts' => self::THEME_SELECTORS['select']['parts'],
			],
			'country' => [
				'base' => self::THEME_SELECTORS['select']['base'],
				'parts' => self::THEME_SELECTORS['select']['parts'],
			],
			'phone' => [
				'base' => [
					...self::THEME_SELECTORS['input'],
				],
				'parts' => \array_merge(self::THEME_SELECTORS['select']['parts'], [
					'select' => self::THEME_SELECTORS['select']['base'],
					'field-content-wrap' => [
						"esf:group-[[data-phone-disable-picker='']]/form:grid",
						"esf:group-[[data-phone-disable-picker='']]/form:gap-10",
						"esf:group-[[data-phone-disable-picker='']]/form:grid-cols-[min(160px)_1fr]",
					]
				]),
			],
			'rating' => [
				'base' => [
					'esf:flex',
					'esf:flex-row',
					'esf:gap-2',
				],
				'parts' => [
					'star' => [
						'esf:sr-only',
					],
					'label' => [
						'esf:text-gray-300',
						'esf:cursor-pointer',
						'esf:[&:has(~_input:checked)]:text-mauve-600',
						'esf:[input:checked_+_&]:text-mauve-600',
						'esf:[input:focus-visible_+_&]:ring-2',
						'esf:[input:focus-visible_+_&]:ring-mauve-600',
						'esf:[input:focus-visible_+_&]:rounded-full',
						'esf:field-disabled:cursor-not-allowed',
						'esf:field-disabled:text-gray-100',
					],
				],
			],
			'loader' => [
				'base' => [
					'esf:hidden',
					'esf:absolute',
					'esf:inset-0',
					'esf:w-full',
					'esf:h-full',
					'esf:form-active:block',
					'esf:form-active:[&_.es-loader\_\_spinner]:animate-spin',
					'esf:form-active:[&_.es-loader\_\_spinner]:duration-500',
				],
				'parts' => [
					'overlay' => [
						'esf:absolute',
						'esf:inset-0',
						'esf:w-full',
						'esf:h-full',
						'esf:bg-white',
						'esf:opacity-50',
						'esf:z-10',
						'esf:transition-opacity',
						'esf:duration-300',
					],
					'spinner' => [
						'esf:sticky',
						'esf:left-1/2',
						'esf:top-1/2',
						'esf:-translate-x-1/2',
						'esf:-translate-y-1/2',
						'esf:z-20',
						'esf:w-40',
						'esf:h-40',
						'esf:flex',
						'esf:border-3',
						'esf:border-x-mauve-600',
						'esf:border-y-transparent',
						'esf:rounded-full',
					],
				],
			],
			'file' => [
				'base' => [
					'esf:group/file',
					'esf:sr-only',
				],
				'parts' => [
					'field' => [
						'esf:group/file-item',
						'esf:[&_.dz-image]:hidden',
						'esf:[&_.dz-success-mark]:hidden',
						'esf:[&_.dz-error-mark]:hidden',
						'esf:[&_.dz-progress]:col-span-2',
						'esf:[&_.dz-progress]:row-start-2',
						'esf:[&_.dz-progress]:bg-gray-100',
						'esf:[&_.dz-progress]:rounded-lg',
						'esf:[&_.dz-progress]:h-5',
						'esf:[&_.dz-progress]:w-full',
						'esf:[&_.dz-progress]:overflow-hidden',
						'esf:[&_.dz-progress]:relative',
						'esf:[&_.dz-upload]:h-full',
						'esf:[&_.dz-upload]:absolute',
						'esf:[&_.dz-upload]:start-0',
						'esf:[&_.dz-upload]:top-0',
						'esf:[&_.dz-upload]:rounded-lg',
						'esf:[&_.dz-upload]:bg-mauve-600',
						'esf:[&_.dz-upload]:transition-width',
						'esf:[&_.dz-error-message]:row-start-3',
						'esf:[&_.dz-error-message]:col-span-2',
						'esf:[&_.dz-error-message]:text-red-500',
						'esf:[&_.dz-error-message]:text-sm',
						'esf:[&_.dz-error-message]:pt-5',
						'esf:[&_.dz-details]:flex',
						'esf:[&_.dz-details]:flex-col',
						'esf:[&_.dz-details]:text-base',
						'esf:[&_.dz-details]:col-start-1',
						'esf:[&_.dz-details]:row-start-1',
						'esf:[&_.dz-details]:text-sm',
						'esf:[&_.dz-details]:min-w-0',
						'esf:[&_.dz-filename]:order-1',
						'esf:[&_.dz-filename]:truncate',
						'esf:[&_.dz-filename]:pr-10',
						'esf:[&_.dz-size]:order-2',
						'esf:[&_.dz-preview]:grid',
						'esf:[&_.dz-preview]:gap-5',
						'esf:[&_.dz-remove]:col-start-2',
						'esf:[&_.dz-remove]:flex',
						'esf:[&_.dz-remove]:items-center',
						'esf:[&_.dz-remove]:justify-end',
						'esf:[&_.dz-remove]:text-mauve-600',
						'esf:[&_.dz-remove]:underline',
						'esf:[&_.dz-remove]:text-xs',
						'esf:[&_.dz-remove]:hover:text-mauve-700',
						'esf:[&_.dz-remove]:focus-ring',
						'esf:[&_.dz-remove]:focus:rounded-lg',
					],
					'button' => [
						'esf-button',
						'esf-button-primary-outline',
						'esf:field-disabled:pointer-events-none',
					],
					'custom-wrap' => [
						'esf:group-[&.dz-max-files-reached]/file-item:opacity-50',
						'esf:group-[&.dz-max-files-reached]/file-item:pointer-events-none',
						'esf:field-error:border-red-500',
						'esf:w-full',
						'esf:rounded-lg',
						'esf:p-20',
						'esf:cursor-pointer',
						'esf:flex',
						'esf:flex-col',
						'esf:justify-center',
						'esf:items-center',
						'esf:gap-10',
						'esf:bg-white',
						'esf:border',
						'esf:border-mauve-200',
						'esf:focus-ring',

						'esf:field-disabled:bg-gray-100',
						'esf:field-disabled:text-gray-400',
						'esf:field-disabled:cursor-not-allowed',
					],
					'info' => [
						'esf:text-gray-500',
					],
				],
			],
			'submit' => [
				'base' => [
					'esf-button',
					// 'esf-button-primary',
					'esf:text-base!',
				],
			],
			'step-navigation-prev' => [
				'base' => [
					'esf-button',
					'esf-button-primary-outline',
					'esf:text-base!',
				],
			],
			'step-navigation-next' => [
				'base' => [
					'esf-button',
					'esf-button-primary',
					'esf:text-base!',
				],
			],
			'progress-bar' => [
				'base' => '',
				'parts' => [
					'item' => '',
					'item-inner' => '',
					'multiflow' => [
						'esf:flex',
						'esf:items-center',
						'esf:justify-center',
						'esf:[&>div]:w-full',
						'esf:[&>div]:h-5',
						'esf:[&>div]:bg-gray-300',
						'esf:[&>div]:rounded-full',
						'esf:[&>div]:me-5',
						'esf:[&>div]:mb-20',
						'esf:[&>div]:block',
						'esf:[&>div.es-form-is-filled]:bg-mauve-700',
						'esf:[&>div.es-form-is-active]:bg-mauve-600',
					],
					'multistep' => [
						'esf:flex',
						'esf:items-center',
						'esf:justify-center',
						'esf:gap-20',
						'esf:border-b',
						'esf:border-mauve-200',
						'esf:pb-20',
						'esf:[&>div>div]:before:content-[""]',
						'esf:[&>div>div]:before:block',
						'esf:[&>div>div]:before:w-20',
						'esf:[&>div>div]:before:h-20',
						'esf:[&>div>div]:before:bg-gray-300',
						'esf:[&>div>div]:before:rounded-full',
						'esf:[&>div>div]:flex',
						'esf:[&>div>div]:flex-col',
						'esf:[&>div>div]:items-center',
						'esf:[&>div>div]:justify-center',
						'esf:[&>div>div]:gap-10',
						'esf:[&>div>div]:text-sm',
						'esf:[&>div.es-form-is-filled>div]:before:bg-mauve-700',
						'esf:[&>div.es-form-is-active>div]:before:bg-mauve-600',
					],
				],
			],
			'step' => [
				'base' => [
					'esf:hidden',
					'esf:form-active:block',
					'esf:col-end-span-12',
					'esf:step-preview:block',
					'esf:step-preview:border',
					'esf:step-preview:border-mauve-200',
					'esf:step-preview:px-20',
					'esf:step-preview:pb-20',
					'esf:step-preview:rounded-lg',
				],
				'parts' => [
					'debug-details' => [
						'esf:hidden',
						'esf:pointer-events-none',
						'esf:border-b',
						'esf:border-mauve-200',
						'esf:p-10',
						'esf:-mx-20',
						'esf:mb-10',
						'esf:bg-gray-100',
						'esf:text-lg',
						'esf:font-bold',
						'esf:text-center',
						'esf:step-preview:block',
					],
					'inner' => [
						'esf:grid',
						'esf:gap-20',
					],
					'navigation' => [
						'esf:col-end-span-12'
					],
					'navigation-inner' => [
						'esf:flex',
						'esf:justify-between',
						'esf:items-center',
						'esf:gap-20',
					],
					'navigation-next' => [
						'esf:ml-auto',
					],
				],
			],
			'form-edit-actions' => [
				'base' => [
					'esf:absolute',
					'esf:top-20',
					'esf:right-20',
					'esf:z-100',
					'esf:bg-white',
					'esf:rounded-lg',
					'esf:border',
					'esf:border-mauve-200',
					'esf:overflow-hidden',
					'esf:invisible',
					'esf:group-hover/form:visible',
				],
				'parts' => [
					'link' => [
						'esf:w-40',
						'esf:h-40',
						'esf:flex',
						'esf:items-center',
						'esf:justify-center',
						'esf:text-mauve-600',
						'esf:cursor-pointer',
						'esf:hover:bg-mauve-700',
						'esf:hover:text-white',
					],
				],
			],
			'global-msg' => [
				'base' => [
					'esf:w-full',
					'esf:rounded-lg',
					'esf:flex',
					'esf:flex-col',
					'esf:gap-2',
					'esf:invisible',
					'esf:border',
					'esf:[&>div]:px-20',
					'esf:[&>div]:py-10',
					'esf:[&>div>div]:font-bold',
					'esf:form-active:visible',
					"esf:data-[status='error']:bg-red-100",
					"esf:data-[status='error']:border-red-500",
					"esf:data-[status='error']:text-red-950",
					"esf:data-[status='success']:bg-green-100",
					"esf:data-[status='success']:border-green-500",
					"esf:data-[status='success']:text-green-950",
				],
			],
		];
	}
}
