<?php

/**
 * Abstract theme class.
 *
 * @package EightshiftForms
 */

declare(strict_types=1);

namespace EightshiftForms\Theme;

/**
 * Abstract theme class.
 */
abstract class AbstractTheme
{
	/**
	 * Admin selectors.
	 *
	 * @var array<mixed>
	 */
	public const THEME_SELECTORS = [
		'input' => [
			'esf:w-full',
			'esf:border',
			'esf:border-gray-300',
			'esf:bg-white',
			'esf:p-12',
			'esf:rounded-md',
			'esf:text-base',
			'esf:text-black',
			'esf:h-46',
			'esf:shadow-none',
			'esf:text-black',
			'esf:placeholder:text-gray-400',
			'esf:group-[&.es-form-is-disabled]/field:bg-gray-50',
			'esf:group-[&.es-form-is-disabled]/field:text-gray-500',
			'esf:group-[&.es-form-is-disabled]/field:cursor-not-allowed',
			'esf:group-[&.es-form-is-disabled]/field:border-gray-300',
			'esf-focus-ring',
			'esf:group-[&.es-form-has-error]/field:border-red-500',
		],
		'help' => [
			'esf:text-gray-400',
			'esf:text-xs',
			'esf:[&_a]:text-mauve-600',
			'esf:[&_a]:underline',
			'esf:[&_a]:hover:text-mauve-700',
			'esf-focus-ring'
		],
		'help-extended' => [
			'esf:[&_ul]:list-disc',
			'esf:[&_ul]:list-inside',
			'esf:[&_ul]:m-0',
			'esf:[&_ul]:p-0',
			'esf:[&_ul]:gap-5',
			'esf:[&_ul]:flex',
			'esf:[&_ul]:flex-col',
			'esf:[&_li]:m-0',
			'esf:[&_code]:text-gray-400',
			'esf:[&_code]:text-xs!',
			'esf:[&_code]:font-mono!',
			'esf:[&_code]:m-0',
			'esf:[&_code]:px-3',
			'esf:[&_code]:py-1',
			'esf:[&_code]:bg-gray-100',
			'esf-focus-ring',
		],
		'after-content' => [
			'esf:text-gray-600',
			'esf:text-xs',
		],
		'label' => [
			'esf:text-base',
			'esf:block',
			'esf:p-0',
		],
		'select' => [
			'base' => [
				'esf:group/select',
				'esf:relative',
				'esf:overflow-hidden',
				'esf:text-base',
				'esf:text-black',
				'esf:[&.is-open]:overflow-visible',
				'esf-focus-ring',

				'esf:data-[type=select-one]:[&_.choices\_\_inner]:h-46',
				'esf:data-[type=select-one]:[&_.choices\_\_inner]:flex',
				'esf:data-[type=select-one]:[&_.choices\_\_inner]:items-center',
				'esf:data-[type=select-one]:[&_.choices\_\_inner]:p-10',
				'esf:data-[type=select-one]:[&_.choices\_\_inner]:pr-55',
				'esf:data-[type=select-one]:[&_.choices\_\_inner]:[&_.choices\_\_placeholder]:text-gray-400',
				'esf:data-[type=select-one]:[&_.choices\_\_inner]:[&_.choices\_\_placeholder]:[&_.choices\_\_button]:hidden',
				'esf:data-[type=select-one]:[&_.choices\_\_inner]:[&_.choices\_\_list]:w-full',
				'esf:data-[type=select-one]:[&_.choices\_\_inner]:[&_.choices\_\_item]:truncate',

				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:w-full',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:min-h-46',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:inline-block',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:pt-6',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:pl-10',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:pr-5',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:align-bottom',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_list]:inline',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_list]:align-top',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:inline-block',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:align-middle',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:rounded-full',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:py-4',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:pl-10',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:pr-35',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:bg-mauve-600',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:text-white',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:relative',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:mr-7',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:mb-6',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:[&_.choices\_\_button]:top-0',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:[&_.choices\_\_button]:right-0',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:[&_.choices\_\_button]:h-full',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:[&_.choices\_\_button]:w-30',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:[&_.choices\_\_button]:text-white',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_item]:[&_.choices\_\_button]:hover:text-mauve-700',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_input--cloned]:border-0',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_input--cloned]:min-h-30',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_input--cloned]:h-30',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_input--cloned]:p-0',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_input--cloned]:m-0',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_input--cloned]:focus:outline-hidden',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_input--cloned]:focus:shadow-none',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_input--cloned]:placeholder:text-gray-400',
				'esf:data-[type=select-multiple]:[&_.choices\_\_inner]:[&_.choices\_\_input--cloned]:text-base',
			],
			'parts' => [
				'select-choices-inner' => [
					'esf:group/select-inner',
					'esf:relative',
					'esf:text-base',
					'esf:text-black',
					'esf:bg-white',
					'esf:border',
					'esf:border-gray-300',
					'esf:rounded-md',
					'esf:overflow-hidden',
					'esf:cursor-pointer',

					'esf:[&_select]:hidden',
					'esf:[&_select]:invisible',
					'esf:[&_select]:select-none',
					'esf:[&_select]:pointer-events-none',

					"esf:after:content-['']",
					"esf:after:h-0",
					"esf:after:w-0",
					"esf:after:border-solid",
					"esf:after:border-transparent",
					"esf:after:border-t-mauve-200",
					"esf:after:border-7",
					"esf:after:absolute",
					"esf:after:right-10",
					"esf:after:top-19",
					"esf:after:pointer-events-none",

					'esf:group-[&.es-form-has-error]/field:border-red-500',

					'esf:group-[&.es-form-is-disabled]/field:text-gray-400',
					'esf:group-[&.es-form-is-disabled]/field:bg-gray-100',
					'esf:group-[&.es-form-is-disabled]/field:cursor-not-allowed',
				],
				'select-list' => [
					'esf:m-0',
					'esf:pl-0',
					'esf:list-none',
				],
				'select-list-dropdown' => [
					'esf:hidden',
					'esf:z-100',
					'esf:absolute',
					'esf:w-full',
					'esf:bg-white',
					'esf:border',
					'esf:border-mauve-200',
					'esf:top-full',
					'esf:inset-x-0',
					'esf:mt-2',
					'esf:rounded-md',
					'esf:overflow-hidden',
					'esf:break-all',

					'esf:group-[&.is-open]/select:block',
					'esf:group-[&.es-form-is-disabled]/field:hidden!',

					'esf:[&_.choices\_\_list]:relative',
					'esf:[&_.choices\_\_list]:max-h-300',
					'esf:[&_.choices\_\_list]:overflow-auto',
					'esf:[&_.choices\_\_list]:will-change-scroll',

					'esf:[&_.choices\_\_item]:relative',
					'esf:[&_.choices\_\_item]:p-10',

					'esf:[&_.choices\_\_placeholder]:hidden',
					'esf:[&_.choices\_\_placeholder]:invisible',
					'esf:[&_.choices\_\_placeholder]:select-none',
					'esf:[&_.choices\_\_placeholder]:pointer-events-none',

					'esf:[&_.choices\_\_input]:w-full!',
					'esf:[&_.choices\_\_input]:min-w-full!',
					'esf:[&_.choices\_\_input]:p-10',
					'esf:[&_.choices\_\_input]:border-0',
					'esf:[&_.choices\_\_input]:border-b',
					'esf:[&_.choices\_\_input]:border-mauve-200',
					'esf:[&_.choices\_\_input]:rounded-none',
					'esf:[&_.choices\_\_input]:bg-transparent',
					'esf:[&_.choices\_\_input]:focus:outline-hidden',
					'esf:[&_.choices\_\_input]:focus:shadow-none',

					'esf:[&_.choices\_\_item--selectable]:cursor-pointer',
					'esf:[&_.choices\_\_item--selectable]:hover:bg-mauve-600/30',
					'esf:[&_.choices\_\_item--selectable]:[&.is-highlighted]:bg-mauve-600/30',
					'esf:[&_.choices\_\_item--selectable]:[&.is-selected]:bg-mauve-600',
					'esf:[&_.choices\_\_item--selectable]:[&.is-selected]:text-white',

					"esf:[&_.choices\_\_item[data-option-is-hidden='1']]:hidden",
					"esf:[&_.choices\_\_item[data-option-is-hidden='1']]:select-none",
					"esf:[&_.choices\_\_item[data-option-is-hidden='1']]:invisible",
					"esf:[&_.choices\_\_item[data-option-is-hidden='1']]:pointer-events-none",
				],
				'select-item-disabled' => [
					'esf:opacity-50',
					'esf:cursor-not-allowed',
				],
				'select-button' => [
					'esf:appearance-none',
					'esf:border-0',
					'esf:bg-transparent',
					'esf:bg-no-repeat',
					'esf:bg-center',
					'esf:cursor-pointer',
					'esf:p-0',
					'esf:absolute',
					'esf:top-8',
					'esf:right-30',
					'esf:text-lg',
					'esf:w-29',
					'esf:h-29',
					'esf:flex',
					'esf:items-center',
					'esf:justify-center',
					'esf:text-mauve-600',
					'esf:hover:text-mauve-700',
					'esf-focus-ring',
				]
			],
		],
		'checkbox' => [
			'parts' => [
				'input' => [
					'esf:relative',
					'esf:appearance-none',
					'esf:bg-white',
					'esf:border',
					'esf:items-center',
					'esf:mx-0!',
					'esf:my-auto!',
					'esf:shadow-none',
					'esf:transition',
					'esf:cursor-pointer',
					'esf:border-gray-300',

					'esf:after:flex',
					'esf:after:items-center',
					'esf:after:justify-center',
					'esf:after:text-base',
					'esf:after:transition',
					'esf:after:absolute',

					'esf:checked:bg-mauve-500',
					'esf:checked:border-mauve-500',

					'esf:is-check:size-24',
					'esf:is-check:after:left-2',
					'esf:is-check:after:top-2',
					'esf:is-check:not-checked:after:opacity-0',
					'esf:is-check:after:text-white',
				],
				'content' => [
					'esf:flex',
					'esf:items-center',
					'esf:gap-10',
				],
			],
		],
	];

	/**
	 * Get the theme selectors for admin and frontend.
	 *
	 * @return array<string, mixed>
	 */
	public function getTheme(): array
	{
		return [
			'forms' => [
				'base' => [
					'esf:relative',
					'esf:box-mauve-200',
					'esf:[&_*]:box-mauve-200',
					'esf:[&_:after]:box-mauve-200',
					'esf:[&_:before]:box-mauve-200',
				],
			],
			'form' => [
				'base' => [
					'esf:group/form',
					'esf:flex',
					'esf:flex-col',
					'esf:gap-10',
					'esf:text-base',
					'esf:[&_*]:transition-colors',
					'esf:[&_*]:duration-300',
				],
				'parts' => [
					'fields' => [
						'esf:grid',
						'esf:gap-20',
						'esf:grid-cols-12',
					],
				],
			],
			'field' => [
				'base' => [
					'esf:group/field',
					'esf:relative',
					'esf:flex',
					'esf:flex-col',
					'esf:gap-10',
					'esf:border-none',
					'esf:min-w-0',
					'esf:col-span-[var(--es-field-width-tw,12)]',
				],
				'parts' => [
					'inner' => [
						'esf:flex',
						'esf:flex-col',
						'esf:gap-5',
					],
					'content' => [
						'esf:flex',
						'esf:flex-col',
						'esf:gap-5',
					],
					'content-wrap' => [
						'esf:flex',
						'esf:flex-col',
						'esf:gap-10',
					],
					'label' => [
						...self::THEME_SELECTORS['label'],
						'esf:group/label',
					],
					'label-inner' => [
						"esf:group-[&.es-field\_\_label--is-required]/label:after:content-['*']",
						"esf:group-[&.es-field\_\_label--is-required]/label:after:text-red-500",
						"esf:group-[&.es-field\_\_label--is-required]/label:after:text-base",
						"esf:group-[&.es-field\_\_label--is-required]/label:after:font-semibold",
						"esf:group-[&.es-field\_\_label--is-visually-hidden]/label:sr-only",
					],
					'help' => self::THEME_SELECTORS['help'],
					'suffix-content' => self::THEME_SELECTORS['after-content'],
					'before-content' => self::THEME_SELECTORS['after-content'],
					'after-content' => self::THEME_SELECTORS['after-content'],
					'debug' => [
						'esf:opacity-0',
						'esf:text-xs',
						'esf:text-gray-500',
						'esf:p-5',
						'esf:border',
						'esf:border-mauve-200',
						'esf:rounded-md',
						'esf:bg-gray-100',
						'esf:pointer-events-none',
						'esf:absolute',
						'esf:right-0',
						'esf:top-0',
						'esf:z-10',
						'esf:bg-white',
						'esf:transition-opacity',
						'esf:duration-300',
						'esf:group-hover/field:opacity-100',
					],
					'error' => [
						'esf:text-red-500',
						'esf:text-sm',
						'esf:hidden',
						'esf:group-[&.es-form-has-error]/field:block',
					],
				],
			],
			'input' => [
				'base' => self::THEME_SELECTORS['input'],
			],
			'date' => [
				'base' => self::THEME_SELECTORS['input'],
				'parts' => [
					'picker' => [
						// Picker is not part of the form.
						'esf:[&_*]:transition-colors',
						'esf:[&_*]:duration-300',
						'esf:[&_*]:focus:outline-2',
						'esf:[&_*]:focus:outline-offset-2',
						'esf:[&_*]:focus:outline-mauve-600',
						'esf:[&_*]:focus:shadow-none',
						'esf:[&_*]:focus:rounded-md',
						'esf:text-black',
						'esf:shadow-none',
						'esf:rounded-md',
						'esf:border',
						'esf:border-mauve-200',
						'esf:text-base',
						'esf:[&_.flatpickr-day]:hover:bg-mauve-600/30',
						'esf:[&_.flatpickr-day]:hover:border-mauve-600/30',
						'esf:[&_.flatpickr-day]:focus:bg-mauve-600/30',
						'esf:[&_.flatpickr-day]:focus:border-mauve-600/30',
						'esf:[&_.selected]:bg-mauve-600',
						'esf:[&_.selected]:border-mauve-600',
						'esf:[&_.selected]:hover:bg-mauve-600',
						'esf:[&_.selected]:hover:border-mauve-600',
						'esf:[&_.selected]:focus:bg-mauve-600',
						'esf:[&_.selected]:focus:border-mauve-600',
						'esf:[&_.today]:border-mauve-200',
						'esf:[&_.today]:hover:bg-mauve-600/30',
						'esf:[&_.today]:hover:border-mauve-600/30',
						'esf:[&_.today]:hover:text-black',
						'esf:[&_.today]:focus:bg-mauve-600/30',
						'esf:[&_.today]:focus:border-mauve-600/30',
						'esf:[&_.today]:focus:text-black',
						'esf:[&_.flatpickr-next-month:hover>svg]:fill-mauve-600',
						'esf:[&_.flatpickr-prev-month:hover>svg]:fill-mauve-600',
					]
				]
			],
			'textarea' => [
				'base' => [
					...self::THEME_SELECTORS['input'],
					'esf:min-h-200',
					'esf:h-auto',
				],
			],
			'checkbox' => [
				'parts' => [
					'input' => [
						...self::THEME_SELECTORS['checkbox']['parts']['input'],
						'esf:is-check:rounded-md',
						'esf:is-check:after:content-["✓"]',
						'esf:is-check:after:size-18',
					],
					'content' => self::THEME_SELECTORS['checkbox']['parts']['content'],
					'label' => self::THEME_SELECTORS['label'],
					'help' => self::THEME_SELECTORS['help'],
				],
			],
			'radio' => [
				'parts' => [
					'input' => [
						...self::THEME_SELECTORS['checkbox']['parts']['input'],
						'esf:is-check:rounded-full',
						'esf:is-check:after:content-["•"]',
						'esf:is-check:after:w-18',
						'esf:is-check:after:h-13',
						'esf:is-check:after:text-5xl',
					],
					'content' => self::THEME_SELECTORS['checkbox']['parts']['content'],
					'label' => self::THEME_SELECTORS['label'],
					'help' => self::THEME_SELECTORS['help'],
				],
			],
			'range' => [
				'base' => [
					'esf:appearance-none',
					'esf:p-0',
					'esf:m-0',
					'esf:block-size-10',
					'esf:w-full',
					'esf:bg-none',
					'esf:focus:outline-hidden',
					'esf:focus:shadow-none',
					'esf:group-[&.es-form-is-disabled]/field:cursor-not-allowed',

					'esf:[&::-webkit-slider-runnable-track]:appearance-none',
					'esf:[&::-webkit-slider-runnable-track]:bg-white',
					'esf:[&::-webkit-slider-runnable-track]:border',
					'esf:[&::-webkit-slider-runnable-track]:border-mauve-200',
					'esf:[&::-webkit-slider-runnable-track]:rounded-full',
					'esf:[&::-webkit-slider-runnable-track]:h-10',
					'esf:[&::-webkit-slider-runnable-track]:w-full',
					'esf:group-[&.es-form-is-disabled]/field:[&::-webkit-slider-runnable-track]:border-gray-100',

					'esf:[&::-moz-range-track]:appearance-none',
					'esf:[&::-moz-range-track]:bg-white',
					'esf:[&::-moz-range-track]:border',
					'esf:[&::-moz-range-track]:border-mauve-200',
					'esf:[&::-moz-range-track]:rounded-full',
					'esf:[&::-moz-range-track]:h-10',
					'esf:[&::-moz-range-track]:w-full',
					'esf:group-[&.es-form-is-disabled]/field:[&::-moz-range-track]:border-gray-100',

					'esf:[&::-webkit-slider-thumb]:appearance-none',
					'esf:[&::-webkit-slider-thumb]:bg-mauve-600',
					'esf:[&::-webkit-slider-thumb]:border-mauve-600',
					'esf:[&::-webkit-slider-thumb]:rounded-full',
					'esf:[&::-webkit-slider-thumb]:h-20',
					'esf:[&::-webkit-slider-thumb]:w-20',
					'esf:[&::-webkit-slider-thumb]:-mt-5',
					'esf:[&::-webkit-slider-thumb]:cursor-pointer',
					'esf:[&::-webkit-slider-thumb]:transition-colors',
					'esf:[&::-webkit-slider-thumb]:duration-300',
					'esf:focus:[&::-webkit-slider-thumb]:outline-2',
					'esf:focus:[&::-webkit-slider-thumb]:outline-offset-2',
					'esf:focus:[&::-webkit-slider-thumb]:outline-mauve-600',
					'esf:focus:[&::-webkit-slider-thumb]:shadow-none',
					'esf:focus:[&::-webkit-slider-thumb]:rounded-full',

					'esf:[&::-moz-range-thumb]:appearance-none',
					'esf:[&::-moz-range-thumb]:bg-mauve-600',
					'esf:[&::-moz-range-thumb]:border-mauve-600',
					'esf:[&::-moz-range-thumb]:rounded-full',
					'esf:[&::-moz-range-thumb]:h-20',
					'esf:[&::-moz-range-thumb]:w-20',
					'esf:[&::-moz-range-thumb]:-mt-5',
					'esf:[&::-moz-range-thumb]:cursor-pointer',
					'esf:[&::-moz-range-thumb]:transition-colors',
					'esf:[&::-moz-range-thumb]:duration-300',
					'esf:focus:[&::-moz-range-thumb]:outline-2',
					'esf:focus:[&::-moz-range-thumb]:outline-offset-2',
					'esf:focus:[&::-moz-range-thumb]:outline-mauve-600',
					'esf:focus:[&::-moz-range-thumb]:shadow-none',
					'esf:focus:[&::-moz-range-thumb]:rounded-full',

					'esf:[&::-moz-range-progress]:bg-mauve-600',
					'esf:[&::-moz-range-progress]:appearance-none',
					'esf:[&::-moz-range-progress]:rounded-full',
					'esf:[&::-moz-range-progress]:h-10',
					'esf:[&::-moz-range-progress]:w-full',
					'esf:disabled:[&::-moz-range-progress]:bg-gray-100',
				],
				'parts' => [
					'min' => '',
					'max' => '',
					'current' => '',
					'output' => [
						'esf:flex',
						'esf:flex-row',
						'esf:items-center',
						'esf:justify-between',
						'esf:gap-5',
						'esf:text-sm',
					],
					'custom' => self::THEME_SELECTORS['input'],
					'field-content-wrap' => [
						"esf:group-[[data-has-custom-range-input='1']]/field:grid",
						"esf:group-[[data-has-custom-range-input='1']]/field:gap-10",
						"esf:group-[[data-has-custom-range-input='1']]/field:grid-cols-[1fr_min(140px)]",
					],
				],
			],
			'select' => [
				'base' => self::THEME_SELECTORS['select']['base'],
				'parts' => self::THEME_SELECTORS['select']['parts'],
			],
			'country' => [
				'base' => self::THEME_SELECTORS['select']['base'],
				'parts' => self::THEME_SELECTORS['select']['parts'],
			],
			'phone' => [
				'base' => [
					...self::THEME_SELECTORS['input'],
				],
				'parts' => \array_merge(self::THEME_SELECTORS['select']['parts'], [
					'select' => self::THEME_SELECTORS['select']['base'],
					'field-content-wrap' => [
						"esf:group-[[data-phone-disable-picker='']]/form:grid",
						"esf:group-[[data-phone-disable-picker='']]/form:gap-10",
						"esf:group-[[data-phone-disable-picker='']]/form:grid-cols-[min(160px)_1fr]",
					]
				]),
			],
			'rating' => [
				'base' => [
					'esf:flex',
					'esf:flex-row',
					'esf:gap-2',
				],
				'parts' => [
					'star' => [
						'esf:sr-only',
					],
					'label' => [
						'esf:text-gray-300',
						'esf:cursor-pointer',
						'esf:[&:has(~_input:checked)]:text-mauve-600',
						'esf:[input:checked_+_&]:text-mauve-600',
						'esf:[input:focus-visible_+_&]:outline-2',
						'esf:[input:focus-visible_+_&]:outline-offset-2',
						'esf:[input:focus-visible_+_&]:outline-mauve-600',
						'esf:[input:focus-visible_+_&]:shadow-none',
						'esf:[input:focus-visible_+_&]:rounded-full',
						'esf:group-[&.es-form-is-disabled]/field:cursor-not-allowed',
						'esf:group-[&.es-form-is-disabled]/field:text-gray-100',
					],
				],
			],
			'loader' => [
				'base' => [
					'esf:hidden',
					'esf:absolute',
					'esf:inset-0',
					'esf:w-full',
					'esf:h-full',
					'esf:[&.es-form-is-active]:block',
					'esf:[&.es-form-is-active]:[&_.es-loader\_\_spinner]:animate-spin',
					'esf:[&.es-form-is-active]:[&_.es-loader\_\_spinner]:duration-500',
				],
				'parts' => [
					'overlay' => [
						'esf:absolute',
						'esf:inset-0',
						'esf:w-full',
						'esf:h-full',
						'esf:bg-white',
						'esf:opacity-50',
						'esf:z-10',
						'esf:transition-opacity',
						'esf:duration-300',
					],
					'spinner' => [
						'esf:sticky',
						'esf:left-1/2',
						'esf:top-1/2',
						'esf:-translate-x-1/2',
						'esf:-translate-y-1/2',
						'esf:z-20',
						'esf:w-40',
						'esf:h-40',
						'esf:flex',
						'esf:border-3',
						'esf:border-x-mauve-600',
						'esf:border-y-transparent',
						'esf:rounded-full',
					],
				],
			],
			'file' => [
				'base' => [
					'esf:group/file',
					'esf:sr-only',
				],
				'parts' => [
					'field' => [
						'esf:group/file-item',
						'esf:[&_.dz-image]:hidden',
						'esf:[&_.dz-success-mark]:hidden',
						'esf:[&_.dz-error-mark]:hidden',
						'esf:[&_.dz-progress]:col-span-2',
						'esf:[&_.dz-progress]:row-start-2',
						'esf:[&_.dz-progress]:bg-gray-100',
						'esf:[&_.dz-progress]:rounded-md',
						'esf:[&_.dz-progress]:h-5',
						'esf:[&_.dz-progress]:w-full',
						'esf:[&_.dz-progress]:overflow-hidden',
						'esf:[&_.dz-progress]:relative',
						'esf:[&_.dz-upload]:h-full',
						'esf:[&_.dz-upload]:absolute',
						'esf:[&_.dz-upload]:start-0',
						'esf:[&_.dz-upload]:top-0',
						'esf:[&_.dz-upload]:rounded-md',
						'esf:[&_.dz-upload]:bg-mauve-600',
						'esf:[&_.dz-upload]:transition-width',
						'esf:[&_.dz-error-message]:row-start-3',
						'esf:[&_.dz-error-message]:col-span-2',
						'esf:[&_.dz-error-message]:text-red-500',
						'esf:[&_.dz-error-message]:text-sm',
						'esf:[&_.dz-error-message]:pt-5',
						'esf:[&_.dz-details]:flex',
						'esf:[&_.dz-details]:flex-col',
						'esf:[&_.dz-details]:text-base',
						'esf:[&_.dz-details]:col-start-1',
						'esf:[&_.dz-details]:row-start-1',
						'esf:[&_.dz-details]:text-sm',
						'esf:[&_.dz-details]:min-w-0',
						'esf:[&_.dz-filename]:order-1',
						'esf:[&_.dz-filename]:truncate',
						'esf:[&_.dz-filename]:pr-10',
						'esf:[&_.dz-size]:order-2',
						'esf:[&_.dz-preview]:grid',
						'esf:[&_.dz-preview]:gap-5',
						'esf:[&_.dz-remove]:col-start-2',
						'esf:[&_.dz-remove]:flex',
						'esf:[&_.dz-remove]:items-center',
						'esf:[&_.dz-remove]:justify-end',
						'esf:[&_.dz-remove]:text-mauve-600',
						'esf:[&_.dz-remove]:underline',
						'esf:[&_.dz-remove]:text-xs',
						'esf:[&_.dz-remove]:hover:text-mauve-700',
						'esf:[&_.dz-remove]:focus:outline-2',
						'esf:[&_.dz-remove]:focus:outline-offset-2',
						'esf:[&_.dz-remove]:focus:outline-mauve-600',
						'esf:[&_.dz-remove]:focus:shadow-none',
						'esf:[&_.dz-remove]:focus:rounded-md',
					],
					'button' => [
						'esf-button',
						'esf-button-primary-outline',
						'esf:group-[&.es-form-is-disabled]/field:pointer-events-none',
					],
					'custom-wrap' => [
						'esf:group-[&.dz-max-files-reached]/file-item:opacity-50',
						'esf:group-[&.dz-max-files-reached]/file-item:pointer-events-none',
						'esf:group-[&.es-form-has-error]/file-item:border-red-500',
						'esf:w-full',
						'esf:rounded-md',
						'esf:p-20',
						'esf:cursor-pointer',
						'esf:flex',
						'esf:flex-col',
						'esf:justify-center',
						'esf:items-center',
						'esf:gap-10',
						'esf:bg-white',
						'esf:border',
						'esf:border-mauve-200',
						'esf-focus-ring',

						'esf:group-[&.es-form-is-disabled]/field:bg-gray-100',
						'esf:group-[&.es-form-is-disabled]/field:text-gray-400',
						'esf:group-[&.es-form-is-disabled]/field:cursor-not-allowed',
					],
					'info' => [
						'esf:text-gray-500',
					],
				],
			],
			'submit' => [
				'base' => [
					'esf-button',
					'esf-button-primary',
					'esf:text-base!',
				],
			],
			'step-navigation-prev' => [
				'base' => [
					'esf-button',
					'esf-button-primary-outline',
					'esf:text-base!',
				],
			],
			'step-navigation-next' => [
				'base' => [
					'esf-button',
					'esf-button-primary',
					'esf:text-base!',
				],
			],
			'progress-bar' => [
				'base' => '',
				'parts' => [
					'item' => '',
					'item-inner' => '',
					'multiflow' => [
						'esf:flex',
						'esf:items-center',
						'esf:justify-center',
						'esf:[&>div]:w-full',
						'esf:[&>div]:h-5',
						'esf:[&>div]:bg-gray-300',
						'esf:[&>div]:rounded-full',
						'esf:[&>div]:me-5',
						'esf:[&>div]:mb-20',
						'esf:[&>div]:block',
						'esf:[&>div]:bg-mauve-600',
						'esf:[&>div.es-form-is-filled]:block',
						'esf:[&>div.es-form-is-filled]:bg-mauve-700',
						'esf:[&>div.es-form-is-active]:block',
						'esf:[&>div.es-form-is-active]:bg-mauve-600',
					],
					'multistep' => [
						'esf:flex',
						'esf:items-center',
						'esf:justify-center',
						'esf:gap-20',
						'esf:border-b',
						'esf:border-mauve-200',
						'esf:pb-20',
						'esf:[&>div>div]:before:content-[""]',
						'esf:[&>div>div]:before:block',
						'esf:[&>div>div]:before:w-20',
						'esf:[&>div>div]:before:h-20',
						'esf:[&>div>div]:before:bg-gray-300',
						'esf:[&>div>div]:before:rounded-full',
						'esf:[&>div>div]:flex',
						'esf:[&>div>div]:flex-col',
						'esf:[&>div>div]:items-center',
						'esf:[&>div>div]:justify-center',
						'esf:[&>div>div]:gap-10',
						'esf:[&>div>div]:text-sm',
						'esf:[&>div.es-form-is-filled>div]:before:bg-mauve-700',
						'esf:[&>div.es-form-is-active>div]:before:bg-mauve-600',
					],
				],
			],
			'step' => [
				'base' => [
					'esf:hidden',
					'esf:[&.es-form-is-active]:block',
					'esf:col-span-12',
					'esf:group-[&.es-form-is-step-preview-active]/form:block',
					'esf:group-[&.es-form-is-step-preview-active]/form:border',
					'esf:group-[&.es-form-is-step-preview-active]/form:border-mauve-200',
					'esf:group-[&.es-form-is-step-preview-active]/form:px-20',
					'esf:group-[&.es-form-is-step-preview-active]/form:pb-20',
					'esf:group-[&.es-form-is-step-preview-active]/form:rounded-md',
					'esf:group-[&.es-form-is-step-preview-active]/form:rounded-md',
				],
				'parts' => [
					'debug-details' => [
						'esf:hidden',
						'esf:pointer-events-none',
						'esf:border-b',
						'esf:border-mauve-200',
						'esf:p-10',
						'esf:-mx-20',
						'esf:mb-10',
						'esf:bg-gray-100',
						'esf:text-lg',
						'esf:font-bold',
						'esf:text-center',
						'esf:group-[&.es-form-is-step-preview-active]/form:block',
					],
					'inner' => [
						'esf:grid',
						'esf:gap-20',
					],
					'navigation' => [
						'esf:col-span-12'
					],
					'navigation-inner' => [
						'esf:flex',
						'esf:justify-between',
						'esf:items-center',
						'esf:gap-20',
					],
					'navigation-next' => [
						'esf:ml-auto',
					],
				],
			],
			'form-edit-actions' => [
				'base' => [
					'esf:absolute',
					'esf:top-20',
					'esf:right-20',
					'esf:z-100',
					'esf:bg-white',
					'esf:rounded-md',
					'esf:border',
					'esf:border-mauve-200',
					'esf:overflow-hidden',
					'esf:invisible',
					'esf:group-hover/form:visible',
				],
				'parts' => [
					'link' => [
						'esf:w-40',
						'esf:h-40',
						'esf:flex',
						'esf:items-center',
						'esf:justify-center',
						'esf:text-mauve-600',
						'esf:cursor-pointer',
						'esf:hover:bg-mauve-700',
						'esf:hover:text-white',
					],
				],
			],
			'global-msg' => [
				'base' => [
					'esf:w-full',
					'esf:rounded-md',
					'esf:flex',
					'esf:flex-col',
					'esf:gap-2',
					'esf:invisible',
					'esf:border',
					'esf:[&>div]:px-20',
					'esf:[&>div]:py-10',
					'esf:[&>div>div]:font-bold',
					"esf:[&.es-form-is-active]:visible",
					"esf:data-[status='error']:bg-red-100",
					"esf:data-[status='error']:border-red-500",
					"esf:data-[status='error']:text-red-950",
					"esf:data-[status='success']:bg-green-100",
					"esf:data-[status='success']:border-green-500",
					"esf:data-[status='success']:text-green-950",
				],
			],
		];
	}
}
