name: Build assets on release and create archive
on: 
  push:
    branches:
      - 'refactor'
jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
          node: [14]

    steps:
    - name: 'Checkout refactor branch'
      uses: actions/checkout@refactor

    - name: PHP setup
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    # Install dependencies and handle caching in one go.
    # @link https://github.com/marketplace/actions/install-composer-dependencies
    - name: Install Composer dependencies
      uses: ramsey/composer-install@v1

    - name: Set Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Install node packages
      run: npm install

    - name: Install node packages
      run: npm run build --no-dev --no-progress

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'eightshift-forms.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Add artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        files: eightshift-forms.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
