name: Bundle artifact

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle:
    name: Add zip to release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 'latest' ]
        php: [ '8.2' ]
    steps:
      - name: Bundle artifact
        uses: infinum/eightshift-deploy-actions-public/.github/actions/bundle-artifact@main
        with:
          PROJECT_PATH: '.'
          REPO_NAME: 'eightshift-forms'
          PHP_VERSION: ${{ matrix.php }}
