name: Bundle artifact

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle:
    name: Add zip to release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 'latest' ]
        php: [ '8.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
  
      - name: Bundle theme/plugin
        uses: infinum/eightshift-deploy-actions-public/.github/actions/setup/theme-or-plugin@main
        with:
          PROJECT_PATH: '.'
          NODE_VERSION: ${{ matrix.node }}
          USE_BUN: true
  
      - name: Post install cleanup - project
        uses: infinum/eightshift-deploy-actions-public/.github/actions/cleanup/project@main
        with:
          PROJECT_PATH: '.'
  
      - name: Zip Folder
        shell: bash
        run: |
          mkdir eightshift-forms
          rsync -r --exclude 'eightshift-forms' * eightshift-forms
          zip -rq release.zip eightshift-forms

      - uses : actions/upload-artifact@v4
        with:
          name: release
          path: release.zip
