name: Bundle artifact

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bundle:
    name: Add zip to artifact
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ["latest"]
        php: ["8.3"]
    steps:
      - name: Setup WordPress
        uses: infinum/eightshift-deploy-actions-public/.github/actions/setup/wordpress@main
        with:
          PHP_VERSION: ${{ matrix.php }}
          WORDPRESS_GH_ACTIONS: ${{ secrets.WORDPRESS_GH_ACTIONS }}

      - name: Setup custom secrets as environment variables
        shell: bash
        run: |
          wp config set WP_ENVIRONMENT_TYPE 'production'

      - name: Install plugin
        uses: infinum/eightshift-deploy-actions-public/.github/actions/setup/theme-or-plugin@main
        with:
          PROJECT_PATH: "wp-content/plugins/eightshift-forms"
          NODE_VERSION: ${{ matrix.node }}
          USE_BUN: true

      - name: Set cache
        uses: infinum/eightshift-deploy-actions-public/.github/actions/set/cache@main
        with:
          PROJECT_PATH: "wp-content/plugins/eightshift-forms"

      - name: Post install cleanup - plugin
        uses: infinum/eightshift-deploy-actions-public/.github/actions/cleanup/project@main
        with:
          PROJECT_PATH: "wp-content/plugins/eightshift-forms"

      - name: Setup correct folder/file permissions
        uses: infinum/eightshift-deploy-actions-public/.github/actions/set/permissions@main

      - name: Zip Plugin
        shell: bash
        run: |
          zip -rq release.zip wp-content/plugins/eightshift-forms

      - name: Upload zip to artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.zip
