name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  composer:
    name: Composer checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Composer checks
        uses: infinum/eightshift-deploy-actions-public/.github/actions/lint/composer@main
        with:
          PROJECT_PATH: '.'
          WORDPRESS_GH_ACTIONS: ${{ secrets.WORDPRESS_GH_ACTIONS }}

  node:
    name: Run Node checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['latest']
    steps:
      - name: Run Node checks
        uses: infinum/eightshift-deploy-actions-public/.github/actions/lint/node@main
        with:
          PROJECT_PATH: '.'
